[[servers]]
name = "aws_238"
host = "13.213.9.238"
port = 22
user = "centos"
identity_file = "~/.ssh/filecoinwallet.pem"

[[servers]]
name = "aws_prod"
host = "13.229.240.234"
port = 22
user = "centos"
identity_file = "~/.ssh/filecoinwallet.pem"



# aws prod
# nest run deploy_aws_prod
# nest run -s 127.0.0.1:1081 deploy_aws_prod
[[tasks]]
name = "deploy_aws_prod"
build_command = "yarn generate_aws"
deploy_server = ["aws_prod"]
deploy_source = "./dist"
deploy_path = "/app/ants-web/bin"
# deploy_command = "supervisorctl restart ants_api"
# pipeline = ["generate_bundle", "_"]